package report

import (
	"fmt"
	"warehouse-wms-backend/internal/models"
	"github.com/jung-kurt/gofpdf"
)

func GenerateProductLabel(product *models.Product) (*gofpdf.Fpdf, error) {
	pdf := gofpdf.New("P", "mm", "A6", "")
	pdf.AddPage()
	
	// Label Header
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(0, 10, "PRODUCT LABEL", "B", 1, "C", false, 0, "")
	
	pdf.Ln(5)
	
	// SKU & Name
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 10, fmt.Sprintf("SKU: %s", product.SKU))
	pdf.Ln(8)
	
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(0, 10, fmt.Sprintf("Name: %s", product.Name))
	pdf.Ln(8)
	
	pdf.Cell(0, 10, fmt.Sprintf("Category: %s", product.Category))
	pdf.Ln(15)
	
	// Placeholder for Barcode (In a real app, you'd generate a barcode image here)
	pdf.SetFillColor(240, 240, 240)
	pdf.Rect(10, 60, 85, 30, "F")
	pdf.SetFont("Arial", "I", 10)
	pdf.SetXY(10, 70)
	pdf.CellFormat(85, 10, "[ BARCODE SCANNER READY ]", "", 0, "C", false, 0, "")
	
	// Footer
	pdf.SetXY(10, 130)
	pdf.SetFont("Arial", "", 8)
	pdf.Cell(0, 10, "Generated by WMS PRO Enterprise")
	
	return pdf, nil
}

func GenerateOrderInvoice(order *models.Order) (*gofpdf.Fpdf, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	// Header
	pdf.SetFont("Arial", "B", 20)
	pdf.Cell(0, 10, "INVOICE PENJUALAN")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(0, 10, fmt.Sprintf("Order ID: %s", order.OrderNumber))
	pdf.Ln(5)
	pdf.Cell(0, 10, fmt.Sprintf("Tanggal: %s", order.CreatedAt.Format("02 Jan 2006")))
	pdf.Ln(15)
	
	// Customer Info
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 10, "Kepada:")
	pdf.Ln(6)
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(0, 10, order.Customer.Name)
	pdf.Ln(15)
	
	// Table Header
	pdf.SetFillColor(230, 230, 230)
	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(100, 10, "Item Description", "1", 0, "C", true, 0, "")
	pdf.CellFormat(30, 10, "Qty", "1", 0, "C", true, 0, "")
	pdf.CellFormat(50, 10, "Total", "1", 1, "C", true, 0, "")
	
	// Table Body (Mock product data from order)
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(100, 10, "Product ID: " + fmt.Sprint(order.ProductID), "1", 0, "L", false, 0, "")
	pdf.CellFormat(30, 10, fmt.Sprint(order.Quantity), "1", 0, "C", false, 0, "")
	pdf.CellFormat(50, 10, fmt.Sprintf("Rp %.2f", order.TotalPrice), "1", 1, "R", false, 0, "")
	
	// Grand Total
	pdf.Ln(10)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(130, 10, "GRAND TOTAL")
	pdf.CellFormat(50, 10, fmt.Sprintf("Rp %.2f", order.TotalPrice), "B", 1, "R", false, 0, "")
	
	return pdf, nil
}
